config/routes.rb
Dymo::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "visits#index"

  devise_for :users

  get 'reports/index'
  get 'reports/test_statistic'
  get 'reports/summary'
  #get 'reports/migrate_physicians'
  get 'reports/physician_patients'
  get 'reports/peak_time'

  resources :locations do
    resources :tokens, except: [:edit, :update] do
      resources :token_histories, except: [:edit, :update]
      member do
        post :done
        post :discard
      end
    end
  end

  resources :visits, only: [:index, :destroy]
  resources :physicians
  resources :test_groups
  resources :tests
  resources :app_configs

  resources :patients, except: [:index, :destroy] do
    resources :visits, only: [:new, :create, :edit, :update]
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :patient
  belongs_to :location
  #belongs_to :physician
  has_many :physician_visits, dependent: :destroy
  has_many :physicians, through: :physician_visits
  has_many :visit_tests
  has_many :tests, through: :visit_tests

  validates_presence_of :patient_id, :physician_ids
  def self.search(search)
    joins(:patient).where('patients.firstname LIKE ? OR patients.lastname LIKE ? OR patients.middlename LIKE ? OR patients.healthnumber LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_action :set_patient, only: [:new, :create, :edit, :update]
  before_action :set_tests, only: [:new, :create, :edit, :update]

  def index
    if params[:healthcard] && params[:healthcard].length >= 50
      options = parse_healthcard(params[:healthcard])

      patient = Patient.find_by_healthnumber(options[:healthnumber])

      if patient
        patient.health_expiry_date = options[:health_expiry_date]
        patient.version_code = options[:version_code]
        patient.save
        redirect_to new_patient_visit_path(patient)
      else
        patient = Patient.create(options)
        if patient.errors.any?
          redirect_to new_patient_path(patient)
        else
          redirect_to new_patient_visit_path(patient)
        end
      end
    else
      @visits = Visit.search(params[:healthcard]).order("created_at desc").paginate(:per_page => 25, :page => params[:page])

      respond_to do |format|
        format.html
        format.json { render json: @visits }
        format.xml  { render xml: @visits }
      end
    end
  end

  def show
  end

  def new
    @visit = @patient.visits.new
    authorize! :new, @visit
    @visit.visitdate = DateTime.now
    @visit.location = current_location
    @test_groups = TestGroup.order("position ASC")
  end

  def edit
    authorize! :edit, @visit
    @test_groups = TestGroup.order("position ASC")
  end

  def create
    @visit = @patient.visits.new(visit_params)
    authorize! :create, @visit
    @visit.location = current_location
    @visit.visitdate = DateTime.now

    respond_to do |format|
      if @visit.save
        token = @visit.patient.time_in_token(current_user, current_location)
        token.add_visit!

        format.html { redirect_to(@patient, notice: 'Visit was successfully created and token time registered.') }
        format.json  { render json: @visit, status: :created, location: @visit }
        format.xml  { render xml: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json  { render json: @visit.errors, status: :unprocessable_entity }
        format.xml  { render xml: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @visit

    respond_to do |format|
      if @visit.update_attributes(visit_params)
        format.html { redirect_to(@patient, notice: 'Visit was successfully updated.') }
        format.json  { head :no_content }
        format.xml  { head :no_content }
      else
        format.html { render action: "edit" }
        format.json  { render json: @visit.errors, status: :unprocessable_entity }
        format.xml  { render xml: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @visit
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to(visits_url, notice: 'Visit was successfully destroyed.') }
      format.xml  { head :ok }
    end
  end

  private
    def set_visit
      @visit = Visit.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def visit_params
      params.require(:visit).permit(:patient_id, :visitdate, :payment_program, :specimen_priority, :amount, :lab_number, test_ids: [], physician_ids: [])
    end

    def set_tests
      @tests = Test.all.to_a
      @test_groups = @tests.group_by { |t| t.test_group }
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= simple_form_for [@patient, @visit] do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>
    Last Visit: <%= @patient.last_visit_date %>
  </h3>

  <table width="100%">
    <tr>
      <td width="50%" style="vertical-align: top; padding-top: 20px;">
        <div class="input string optional visit_physician">
          <label for="visit_physician" class="string optional control-label">Select Physicians</label>
          <%= f.collection_select :physician_ids, Physician.all, :id, :fullname_with_physician_number, { selected: @visit.physician_ids, include_blank: false }, { multiple: true } %>
        </div>

        <%#= f.hidden_field :physician_id %>
        <%#= f.input :visitdate, as: :string, hint: '(YYYY/MM/DD)', wrapper_html: { class: 'datepicker-swrapper' } %>
        <%= f.hidden_field :visitdate %>
        <br style="clear:left;" /><br />
        <%= f.input :payment_program, collection: [["HCP", "HCP"],["RMB", "RMB"],  ["WSIB", "WSIB"], ["Paid Patient", "Paid Patient"], ["Bill Patient", "Bill Patient"], ["IFH", "IFH"], ["Clinical Trials", "Clinical Trials"]], include_blank: false %>

          <%= f.input :amount %>
        <%= f.input :specimen_priority, collection: [["Routine", "Routine"],["Stat", "Stat"]], include_blank: false %>
      </td>
      <td width="50%">
        <div id="patient-details" style="margin: 0 10px;">
          <a id="edit-patient-link" href="javascript:void(0);" style="float: right;">Edit patient</a>
          <div id="patient_summary" >
            <%= render partial: 'patients/patient_summary', locals: { patient: @patient } %>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div id="test_groups" title="SELECT TESTS">
          <h2 style="margin-left: 20px;">SELECT TESTS</h2>

          <div class="input string optional visit_tests" style="padding-left: 20px;">
            <%= f.collection_select :test_ids1, Test.order("tests.position ASC"), :id, :test_name, { selected: false, include_blank: true, prompt: "Search tests..." } %>
          </div>
          
          <div class="clear">
            <br />
          </div>
          
          <% @test_groups.each_with_index do |test_group, index| %>

            <div class="test-groups" style="float: left; margin-left: 20px; border: solid 1px #ccc; ">
              <h4><%= test_group.name %></h4>
              <div id="tests_check_boxes" class="test-group" >
                <%= f.collection_check_boxes(:test_ids, test_group.tests.order("tests.position ASC"), :id, :test_name) do |b| %>
                  <% b.label(:"data-value" => b.object.id, class: (b.object.visible?(@visit.test_ids) ? "show" : "hide") ) { b.check_box + ' ' + b.text } %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </td>
    </tr>
  </table>


  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(function(){
    $("#physician_name").autocomplete({
      source: "/physicians.json",
      select: function(event, ui){
        $('#visit_physician_id').val(ui.item.val);
      }
    });
  });
</script>

<div id="dialog-patient-edit" style="display: none;" title="EDIT PATIENT">
  <div id="patient-edit-form">
    <%= render 'patients/form' %>
  </div>
</div>

app/views/visits/edit.html.erb
<fieldset class="f-set">
  <legend>Edit Visit</legend>
</fieldset>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Patients</h1>
<%= form_tag visits_path, :method => 'get', :id => "search_form" do %>
  <p>
    <%= text_field_tag :healthcard, params[:healthcard], :class => 'text' %>
    <%= submit_tag "Search", :name => nil %>&nbsp;&nbsp;&nbsp; or &nbsp;&nbsp;&nbsp; <%= link_to 'Add Patient', new_patient_path %>
  </p>
<% end %>
<i>To search patient, type name OR type Health card and Press Search.</i><br />
<i>To swipe card, first clear search text box and swipe card.</i>
<br />  
<h2>Total Visits: <%= @visits.count %></h2>
<table width="100%">
  <tr>
    <th>Location</th>
    <th>OHIP</th>
    <th>Health Expiry</th>
    <th>Lastname</th>
    <th>Firstname</th>

    <th>Birthdate</th>
    <th>Address</th>
    <th>Physician <small>(<u>click to print label</u>)</small></th>
    <th>Visited on</th>
    <th></th>
    <th colspan="2"></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.location.name %></td>
    <td><%= visit.patient.healthnumber %>&nbsp;<%= visit.patient.version_code %></td>
    <td><%= visit.patient.health_expiry_date.nil? ? '' : visit.patient.health_expiry_date.to_formatted_s(:long) %></td>
    <td><%= visit.patient.lastname %></td>
    <td><%= visit.patient.firstname %> &nbsp;<%= visit.patient.middlename %></td>

    <td><%= visit.patient.birthdate.nil? ? '' : visit.patient.birthdate.to_formatted_s(:long) %></td>
    <td>
      <%= visit.patient.address1 %>,
      <%= visit.patient.address2 %>,
      <%= visit.patient.city %>,
      <%= visit.patient.province %>,
      <%= visit.patient.postal_code %>
      <%= visit.patient.home_phone %>(H),
      <%= visit.patient.mobile %>(M)
    </td>
    <td>
      <% visit.physicians.each do |physician| %>
        <%= print_physician_label_link(visit, physician) %><br />
      <% end %>
    </td>
    <td>
      <%= visit.visitdate.nil? ? '' : visit.visitdate.to_formatted_s(:long) %>
    </td>
    <td><%= link_to 'Show', patient_path(visit.patient) %></td>
    <td class="text-center"><%= link_to 'Add New Visit', new_patient_visit_path(visit.patient) %>
</td>
    <td class="text-center">
      <%= link_to 'Edit', edit_patient_visit_path(visit.patient, visit) if can?(:update, visit) %><%= " | " if can?(:destroy, visit) %><%= destroy_link(visit) %>
    </td>

  </tr>
<% end %>
</table>
<br />
<%= will_paginate @visits %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#search').focus();
  });
</script>

app/views/visits/new.html.erb
<fieldset class="f-set">
  <legend>New Visit</legend>
</fieldset>

<%= render 'form' %>

app/views/visits/show.html.erb
<p>
  <b>Patient:</b>
  <%= @visit.patient_id %>
</p>

<p>
  <b>Physician:</b>
  <%= @visit.physician_id %>
</p>


<%= link_to 'Back', visits_path %>