config/routes.rb
Dymo::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "visits#index"

  devise_for :users

  get 'reports/index'
  get 'reports/test_statistic'
  get 'reports/summary'
  #get 'reports/migrate_physicians'
  get 'reports/physician_patients'
  get 'reports/peak_time'

  resources :locations do
    resources :tokens, except: [:edit, :update] do
      resources :token_histories, except: [:edit, :update]
      member do
        post :done
        post :discard
      end
    end
  end

  resources :visits, only: [:index, :destroy]
  resources :physicians
  resources :test_groups
  resources :tests
  resources :app_configs

  resources :patients, except: [:index, :destroy] do
    resources :visits, only: [:new, :create, :edit, :update]
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :visits
  has_many :physicians, :through => :visits
  has_many :tokens
  validates_length_of :healthnumber, :maximum => 13
  validates_length_of :version_code, :maximum => 2
  validates_presence_of :firstname, :lastname

  def self.search(search)
    if search
      where('firstname LIKE ? OR lastname LIKE ? OR middlename LIKE ? OR healthnumber LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
    else
      all
    end
  end

  def new_time_in_token(user, location)
    token = location.tokens.new({
      patient: self,
      no: location.tokens.where("(created_at >= ? AND created_at <= ?)", DateTime.now.beginning_of_day, DateTime.now.end_of_day).size + 1
    })
    token.user = user
    token.save!

    token_history = token.token_histories.build
    token_history.punch_in_time = token.created_at
    token_history.note = "time_in"
    token_history.user = user
    token_history.save!
    token
  end

  def patient_full_name
    "#{lastname} #{firstname} "
  end

  def fullname_with_health_insurance_number
    "#{healthnumber} - #{lastname} #{firstname} #{middlename}"
  end

  def time_in_token(user, location)
    token = location.tokens.where("(created_at >= ? AND created_at <= ?) AND state = ?", DateTime.now.beginning_of_day, DateTime.now.end_of_day, "time_in").first
    unless token
      token = self.new_time_in_token(user, location) 
    else
      token.user = user
    end
    token
  end

  def last_visit
    visits.order("created_at DESC").first
  end

  def last_visit_date
    visit = visits.order("created_at DESC").first
    if visit && !visit.new_record?
      visit.visitdate.blank? ? "" : "#{visit.lab_number} #{visit.visitdate.to_formatted_s(:long)}"
    else
      "First visit"
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.search(params[:search]).order("created_at desc").paginate(per_page: 5, page: params[:page])
  end

  def show
  end

  def new
    @patient = params[:patient].nil? ? Patient.new : Patient.new(patient_params)
    authorize! :new, @patient
    @tests = Test.all.to_a
    @test_groups = @tests.group_by { |t| t.test_group }
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    authorize! :create, @patient

    respond_to do |format|
      if @patient.save
        @token = @patient.new_time_in_token(current_user, current_location)

        print_token

        #Visit.create({ physician_id: params[:physician_id1], patient_id: @patient.id, visitdate: params[:visitdate], payment_program: params[:payment_program], test_ids: params[:test_ids] })

        format.html { redirect_to(location_tokens_path(current_location), notice: 'Patient and Token were successfully created.') }
        format.json  { render json: @patient, status: :created, location: @patient }
        format.xml  { render xml: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json  { render json: @patient.errors, status: :unprocessable_entity }
        format.xml  { render xml: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @patient = Patient.find(params[:id])
    authorize! :create, @patient

    respond_to do |format|
      if @patient.update_attributes(patient_params)
        format.html { redirect_to(@patient, notice => 'Patient was successfully updated.') }
        format.json  { head :no_content }
        format.js
        format.xml  { head :no_content }
      else
        format.html { render action: "edit" }
        format.json  { render json: @patient.errors, status: :unprocessable_entity }
        format.js
        format.xml  { render xml: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @patient
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to(patients_url, notice: 'Patient was successfully destroyed.') }
      format.json  { head :no_content }
      format.xml  { head :no_content }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:healthnumber, :version_code, :health_expiry_date, :lastname, :firstname, :middlename, :gender, :birthdate, :address1, :address2, :city, :province, :postal_code, :home_phone, :mobile, physician_ids: [])
    end

    def print_token
      uri = URI.parse("#{AppConfig.print_token_url}#{@token.id}/#{@token.patient.healthnumber}")
      #res = Net::HTTP.get_response(uri)
    end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for @patient, :class => 'patient_form', data: { remote: true } do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form-table" width="100%">
    <tr>
      <td width="100%">
        <%= f.input :healthnumber %>
        <%= f.input :version_code %>
				<%= f.input :health_expiry_date, :as => :string, :input_html => { :id => 'hedpicker'}, :hint => '(YYYY/MM/DD)', :wrapper_html => { :class => 'datepicker-swrapper'}  %>
        <%= f.input :lastname %>
        <%= f.input :firstname %>
        <%= f.input :middlename %>
        <%= f.input :gender do %>
          <%= f.collection_radio_buttons :gender, [['M','Male'] ,['F', 'Female']], :first, :last, :class => 'radio-collection' %>
        <% end %>
        <%= f.input :birthdate , :as => :string, :input_html => { :id => 'birthdaypicker' }, :hint => '(YYYY/MM/DD)', :wrapper_html => { :class => 'datepicker-swrapper'}  %>
        <%= f.input :address1 %>
        <%= f.input :address2 %>
        <%= f.input :city %>
        <%= f.input :province %>
        <%= f.input :postal_code %>
        <%= f.input :home_phone %>
        <%= f.input :mobile %>
      </td>
    </tr>
  </table>

  <%= f.button :submit %>
<% end %>
<script type="text/javascript">
  $(function(){
    $("#physician_id_text1").autocomplete({
      source: "/physicians.json",
      select: function(event, ui){
        $('#physician_id1').val(ui.item.val);
      }
    });
  });
</script>

app/views/patients/_new_form.html.erb
<%= simple_form_for @patient, :class => 'patient_form' do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form-table" width="100%">
    <tr>
      <td width="100%">
        <%= f.input :healthnumber %>
        <%= f.input :version_code %>
				<%= f.input :health_expiry_date, :as => :string, :input_html => { :id => 'hedpicker'}, :hint => '(YYYY/MM/DD)', :wrapper_html => { :class => 'datepicker-swrapper'}  %>
        <%= f.input :lastname %>
        <%= f.input :firstname %>
        <%= f.input :middlename %>
        <%= f.input :gender do %>
          <%= f.collection_radio_buttons :gender, [['M','Male'] ,['F', 'Female']], :first, :last, :class => 'radio-collection' %>
        <% end %>
        <%= f.input :birthdate , :as => :string, :input_html => { :id => 'birthdaypicker' }, :hint => '(YYYY/MM/DD)', :wrapper_html => { :class => 'datepicker-swrapper'}  %>
        <%= f.input :address1 %>
        <%= f.input :address2 %>
        <%= f.input :city %>
        <%= f.input :province %>
        <%= f.input :postal_code %>
        <%= f.input :home_phone %>
        <%= f.input :mobile %>
      </td>
    </tr>
  </table>

  <%= f.button :submit %>
<% end %>
<script type="text/javascript">
  $(function(){
    $("#physician_id_text1").autocomplete({
      source: "/physicians.json",
      select: function(event, ui){
        $('#physician_id1').val(ui.item.val);
      }
    });
  });
</script>

app/views/patients/_patient_summary.html.erb
<table width="100%" class="no-border">
  <tr>
    <td colspan="2">
      <h1 id="name" class="name">
        <%= @patient.firstname %>&nbsp;<%= @patient.middlename %>&nbsp;<%= @patient.lastname %>
    </td>
  </tr>
  <tr>
    <td width="50%">
    <ul>
        <li style="font-size: 16px; font-weight: bold;">OHIP: <%= patient.healthnumber %>&nbsp;<%= patient.version_code %></li>
        <li class="expire">Expires on: <%= patient.health_expiry_date.nil? ? '' : patient.health_expiry_date.to_formatted_s(:long) %></li>
      </ul>

    </td>
    <td style="text-align: left;">
      <%= patient.gender == 'M' ? 'Male' : 'Female' %><br />
      Birthdate: <%= patient.birthdate.nil? ? '' : patient.birthdate.to_formatted_s(:long) %>
    </td>
  </tr>
  <tr>
    <td style="border-top: solid 1px #ccc;">
      <div class="address" >
        <%= patient.address1 %><br />
        <%= patient.address2 %><br />
        <%= patient.city %><br />
        <%= patient.province %><br />
        <%= patient.postal_code %><br />
      </div>
    </td>
    <td style="border-top: solid 1px #ccc;">
      <div class="contact" style="border: 0 none; font-size: 16px;">
        Home (Ph):&nbsp; <%= patient.home_phone %><br />
        Mobile (Ph):&nbsp;<%= patient.mobile %><br />
      </div>
    </td>
  </tr>
</table>

app/views/patients/edit.html+phone.erb
<%= content_for :title do %>
  Editing Patient
<% end %>
<div role="main" class="ui-content">
  <%= render 'form' %>

  <%= link_to 'Show', @patient %> |
  <%= link_to 'Back', patients_path %>
</div>

app/views/patients/edit.html.erb
<fieldset class="f-set f-patient">
  <legend>Edit Patient</legend>
</fieldset>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', root_path %>

app/views/patients/index.html+phone.erb
<%= content_for :header do %>
  <%= link_to 'Add New Patient', new_patient_path %>
<% end %>
<%= content_for :title do %>
  Listing Patients
<% end %>
<div role="main" class="ui-content">
  <%= form_tag patients_path, :method => 'get', :id => 'patients_search' do %>
    <p>
      <%= text_field_tag :search, params[:search], :class => 'text' %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <br />
  <table data-role="table" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a">
    <thead>
      <tr class="ui-bar-d">
        <th>OHIP</th>
        <th>Health Expiry Date</th>
        <th>Last name</th>
        <th>First name</th>
        <th>Middle name</th>
        <th data-priority="1">Address</th>
        <th data-priority="2">Birthdate</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.healthnumber %> + " " + <%= patient.version_code %></td>
      <td><%= patient.health_expiry_date.nil? ? '' : patient.health_expiry_date.to_formatted_s(:long) %></td>
      <td><%= patient.lastname %></td>
      <td><%= patient.firstname %></td>
      <td><%= patient.middlename %></td>
      <td>
        <%= patient.address1 %><br />
        <%= patient.address2 %><br />
        <%= patient.city %><br />
        <%= patient.province %><br />
        <%= patient.postal_code %><br />
        <%= patient.home_phone %><br />
        <%= patient.mobile %>
      </td>
      <td><%= patient.birthdate.nil? ? '' : patient.birthdate.to_formatted_s(:long) %></td>
      <td><%= link_to 'Show', patient %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      <td><%= link_to 'Destroy', patient, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
  <br />
  <br />
  <%= will_paginate @patients %>
</div>

app/views/patients/index.html.erb
<h1>Listing patients</h1>
<%= form_tag patients_path, :method => 'get', :id => 'patients_search' do %>
  <p>
    <%= text_field_tag :search, params[:search], :class => 'text' %>
    <%= submit_tag "Search", :name => nil %>&nbsp;&nbsp;&nbsp; or &nbsp;&nbsp;&nbsp; <%= link_to 'Add New Patient', new_patient_path %>
  </p>
<% end %>

<br />
<table>
  <tr>
    <th>OHIP</th>
    <th>Health Expiry Date</th>
    <th>Last name</th>
    <th>First name</th>
    <th>Middle name</th>
    <th>Address</th>
    <th>Birthdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.healthnumber %> + " " + <%= patient.version_code %></td>
    <td><%= patient.health_expiry_date.nil? ? '' : patient.health_expiry_date.to_formatted_s(:long) %></td>
    <td><%= patient.lastname %></td>
    <td><%= patient.firstname %></td>
    <td><%= patient.middlename %></td>
    <td>
      <%= patient.address1 %><br />
      <%= patient.address2 %><br />
      <%= patient.city %><br />
      <%= patient.province %><br />
      <%= patient.postal_code %><br />
      <%= patient.home_phone %><br />
      <%= patient.mobile %>
    </td>
    <td><%= patient.birthdate.nil? ? '' : patient.birthdate.to_formatted_s(:long) %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<br />
<%= will_paginate @patients %>

app/views/patients/new.html+phone.erb
<%= content_for :title do %>
  Create new Patient
<% end %>
<div role="main" class="ui-content">
  <%= render 'form' %>

  <%= link_to 'Back', patients_path %>
</div>

app/views/patients/new.html.erb
<fieldset class="f-set f-patient">
  <legend>Add New Patient</legend>
</fieldset>

<%= render 'new_form' %>

<%= link_to 'Back', root_path %>

app/views/patients/show.html+phone.erb
<%= content_for :title do %>
  Patient Info.
<% end %>
<div role="main" class="ui-content">
  <div id="patient-details" >
    <h1 id="name">
      <%= @patient.firstname %>&nbsp;<%= @patient.middlename %>&nbsp;<%= @patient.lastname %>
      <ul>
        <li>OHIP: <%= @patient.healthnumber %>&nbsp;<%= @patient.version_code %></li>
        <li class="expire">Expires on: <%= @patient.health_expiry_date.nil? ? '' : @patient.health_expiry_date.to_formatted_s(:long) %></li>
      </ul>
    </h1>
    <h2 id="heading">
      <%= @patient.gender == 'M' ? 'Male' : 'Female' %>, <%= @patient.marital_status == 'Y' ? 'Married' : 'Unmarried' %><br />
      Birthdate: <%= @patient.birthdate.nil? ? '' : @patient.birthdate.to_formatted_s(:long) %>
    </h2>
    <div class="address-details">
      <div class="address">
        <%= @patient.address1 %><br />
        <%= @patient.address2 %><br />
        <%= @patient.city %><br />
        <%= @patient.province %><br />
        <%= @patient.postal_code %><br />
      </div>
      <div class="contact">
        Home (Ph):&nbsp; <%= @patient.home_phone %><br />
         (Ph):&nbsp;<%= @patient.mobile %><br />
      </div>
      <div class="clear">
      </div>
    </div>
  </div>
  <h3 class="new-visit">Visits:
    <%= link_to '(Add Visit)', :controller => "visits", :action => :new, :id => @patient.id %></h3>
  <table>
    <tr>
      <th>Physician number</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Visited on</th>
      <th></th>
    </tr>

  <% for visit in @patient.visits %>
    <tr>
      <td><%= visit.physician.physician_number %></td>
      <td><%= visit.physician.lastname %></td>
      <td><%= visit.physician.firstname %></td>
      <td><%= visit.physician.middlename %></td>
      <td><%= visit.created_at.strftime("%b %d, %Y") %></td>
      <td><a href="javascript:void(0);" healthNumber="<%= visit.patient.healthnumber %>" expiry="<%= visit.patient.health_expiry_date.nil? ? '' : visit.patient.health_expiry_date.to_formatted_s(:long) %>" birthdate="<%= visit.patient.birthdate.nil? ? '' : visit.patient.birthdate.to_formatted_s(:long) %>" sex="<%= visit.patient.gender %>" address1="<%= visit.patient.address1 %>" address2="<%= visit.patient.address2 %>" homephone="<%= visit.patient.home_phone %>" ="<%= visit.patient.mobile %>"  patientName="<%= visit.patient.lastname + ' ' + visit.patient.firstname + ' ' + visit.patient.middlename %>" physician="<%= visit.physician.lastname + ' ' + visit.physician.firstname + ' ' + visit.physician.middlename %>" visiteddate="<%= visit.created_at.strftime("%b %d, %Y") %>" class="print-label-link">Print Label</a></td>
    </tr>
  <% end %>
  </table>
  <br />
  <br />
  <%= link_to 'edit', edit_patient_path(@patient) %> |
  <%= link_to 'back', patients_path %>
  
</div>

app/views/patients/show.html.erb
<fieldset class="f-set f-patient">
  <legend>Patient Info.</legend>
</fieldset>
<div id="patient-details">
  <h1 id="name" class="name">
    <%= @patient.firstname %>&nbsp;<%= @patient.middlename %>&nbsp;<%= @patient.lastname %>
    <ul>
      <li>OHIP: <%= @patient.healthnumber %>&nbsp;<%= @patient.version_code %></li>
      <li class="expire">Expires on: <%= @patient.health_expiry_date.nil? ? '' : @patient.health_expiry_date.to_formatted_s(:long) %></li>
    </ul>
  </h1>
  <h2 id="heading" class="heading">
    <%= @patient.gender == 'M' ? 'Male' : 'Female' %><br />
    Birthdate: <%= @patient.birthdate.nil? ? '' : @patient.birthdate.to_formatted_s(:long) %>
  </h2>
  <div class="address-details">
    <div class="address">
      <%= @patient.address1 %><br />
      <%= @patient.address2 %><br />
      <%= @patient.city %><br />
      <%= @patient.province %><br />
      <%= @patient.postal_code %><br />
    </div>
    <div class="contact">
      Home (Ph):&nbsp; <%= @patient.home_phone %><br />
      Mobile (Ph):&nbsp;<%= @patient.mobile %><br />
    </div>
    <div class="clear">
    </div>
  </div>
</div>
<h3 class="new-visit">Visits:
  <%= link_to 'Add New Visit', new_patient_visit_path(@patient) %></h3>
<table>
  <tr>
    <th>Location</th>
    <th>Labnumber</th>
    <th>Physician number</th>
    <th> Phyisican Name <small>(<u>click to print label</u>)</small></th>
    <th>Visited on</th>
    <th>Payment program</th>
	  <th>Specimen Priority</th>
	  <th>Amount</th>
    <th>Tests</th>
    <th></th>
  </tr>

<% @patient.visits.order("created_at DESC").each do |visit| %>
  <tr>
    <td><%= visit.location.name %></td>
    <td><%= visit.lab_number %></td>
    <td><%= visit.physicians.map(&:physician_number).join(", ") %></td>
    <td>
      <% visit.physicians.each do |physician| %>
        <%= print_physician_label_link(visit, physician) %><br />
      <% end %>
    </td>
    <td><%= visit.visitdate.nil? ? '' : visit.visitdate.to_formatted_s(:long) %></td>
    <td><%= visit.payment_program %></td>
	  <td><%= visit.specimen_priority %></td>
	  <td><%= visit.amount %></td>
    <td>
      <% visit.tests.each_with_index do |test, index| %>
        <%= "#{test.test_code}" %><%= ", " unless visit.tests.size == (index + 1) %>
      <% end %>
    </td>
    <td>
      <%= link_to 'Edit', edit_patient_visit_path(@patient, visit) if can?(:update, visit) %>
    </td>
  </tr>
<% end %>
</table>
<br />
<br />
<%= link_to 'back', visits_path %>

app/views/patients/update.js.erb
<% if @patient.errors.any? %>
$('#patient-edit-form').html('<%=j render "form" %>');
<% else %>
$('#patient_summary').html('<%=j render partial: "patients/patient_summary", locals: { patient: @patient } %>');
$('#dialog-patient-edit').dialog("close");

<% end %>