config/routes.rb
Dymo::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "visits#index"

  devise_for :users

  get 'reports/index'
  get 'reports/test_statistic'
  get 'reports/summary'
  #get 'reports/migrate_physicians'
  get 'reports/physician_patients'
  get 'reports/peak_time'

  resources :locations do
    resources :tokens, except: [:edit, :update] do
      resources :token_histories, except: [:edit, :update]
      member do
        post :done
        post :discard
      end
    end
  end

  resources :visits, only: [:index, :destroy]
  resources :physicians
  resources :test_groups
  resources :tests
  resources :app_configs

  resources :patients, except: [:index, :destroy] do
    resources :visits, only: [:new, :create, :edit, :update]
  end

end

app/models/token_history.rb
class TokenHistory < ActiveRecord::Base
  belongs_to :token
  belongs_to :user
end

app/controllers/token_histories_controller.rb
class TokenHistoriesController < ApplicationController
  #load_and_authorize_resource
  before_action :set_token_history, only: [:show, :edit, :update, :destroy]
  before_action :set_token

  # GET /token_histories
  # GET /token_histories.json
  def index
    @token_histories = TokenHistory.all
  end

  # GET /token_histories/1
  # GET /token_histories/1.json
  def show
  end

  # GET /token_histories/new
  def new
    if @token.discarded?
      redirect_to tokens_path
    else
      @token_history = @token.token_histories.new({ note: params[:note] })
    end
  end

  # GET /token_histories/1/edit
  def edit
  end

  # POST /token_histories
  # POST /token_histories.json
  def create
    @token_history = @token.token_histories.new(token_history_params)
    @token_history.user = current_user
    authorize! :create, @token_history
    @token_history.punch_in_time = DateTime.now

    respond_to do |format|
      if @token_history.save
        if @token_history.note == "discarded"
          @token.user = current_user
          @token.discard!
        end
        format.html { redirect_to [current_location, @token], notice: 'Token punched successfully created.' }
        format.json { render :show, status: :created, location: @token_history }
      else
        format.html { render :new }
        format.json { render json: @token_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /token_histories/1
  # PATCH/PUT /token_histories/1.json
  def update
    respond_to do |format|
      if @token_history.update(token_history_params)
        format.html { redirect_to @token, notice: 'Token history was successfully updated.' }
        format.json { render :show, status: :ok, location: @token_history }
      else
        format.html { render :edit }
        format.json { render json: @token_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /token_histories/1
  # DELETE /token_histories/1.json
  def destroy
    @token_history.destroy
    respond_to do |format|
      format.html { redirect_to [current_location, @token], notice: 'Token history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_token
      @token = Token.find(params[:token_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_token_history
      @token_history = TokenHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_history_params
      params.require(:token_history).permit(:token_id, :punch_in_time, :note, :comment)
    end
end

app/helpers/token_histories_helper.rb
module TokenHistoriesHelper
end

app/views/token_histories/_form.html.erb
<%= simple_form_for [current_location, @token, @token_history] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :note %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <% if params[:note] == "discarded" %>
      <%= f.button :submit, "Discard token" %>
    <% else %>
      <%= f.button :submit %>
    <% end %>
  </div>
<% end %>

app/views/token_histories/edit.html.erb
<h1>Editing token_history</h1>

<%= render 'form' %>

<%= link_to 'Show', [@token, @token_history] %> |
<%= link_to 'Back', token_path(@token) %>

app/views/token_histories/index.html.erb
<h1>Listing token_histories</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Punch in time</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @token_histories.each do |token_history| %>
      <tr>
        <td><%= token_history.token_id %></td>
        <td><%= token_history.punch_in_time %></td>
        <td><%= token_history.note %></td>
        <td><%= link_to 'Show', token_history %></td>
        <td><%= link_to 'Edit', edit_token_history_path(token_history) %></td>
        <td><%= link_to 'Destroy', token_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token history', new_token_token_history_path(@token) %>

app/views/token_histories/new.html+phone.erb
<%= content_for :title do %>
  Create new Visit
<% end %>
<div role="main" class="ui-content">
  <%= render 'form' %>

  <%= link_to 'Back', tokens_path %>
</div>

app/views/token_histories/new.html.erb
<fieldset class="f-set f-patient">
  <legend><%= params[:note] == "discarded" ? "Discard token" : "Punch token" %></legend>
</fieldset>

<h1>Token #: <%= @token.no %> <span class="<%= @token.state %>">(<%= @token.state.gsub('_', ' ').capitalize %>)</span></h1>
<p>
  <strong>Patient:</strong>
  <%= @token.patient.fullname_with_health_insurance_number %> <%= @token.patient.version_code %>
</p>
<br />
<br />
<%= render 'form' %>

<%= link_to 'Back', location_tokens_path(current_location) %>

app/views/token_histories/show.html.erb
<p>
  <strong>Token:</strong>
  <%= @token_history.token_id %>
</p>

<p>
  <strong>Punch in time:</strong>
  <%= @token_history.punch_in_time %>
</p>

<p>
  <strong>Note:</strong>
  <%= @token_history.note %>
</p>

<%= link_to 'Edit', edit_token_token_history_path(@token, @token_history) %> |
<%= link_to 'Back', token_path(@token) %>