config/routes.rb
Dymo::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "visits#index"

  devise_for :users

  get 'reports/index'
  get 'reports/test_statistic'
  get 'reports/summary'
  #get 'reports/migrate_physicians'
  get 'reports/physician_patients'
  get 'reports/peak_time'

  resources :locations do
    resources :tokens, except: [:edit, :update] do
      resources :token_histories, except: [:edit, :update]
      member do
        post :done
        post :discard
      end
    end
  end

  resources :visits, only: [:index, :destroy]
  resources :physicians
  resources :test_groups
  resources :tests
  resources :app_configs

  resources :patients, except: [:index, :destroy] do
    resources :visits, only: [:new, :create, :edit, :update]
  end

end

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedHealth</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "mobile" %>
  <%= javascript_include_tag "mobile" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div data-role="page">
    <div data-role="panel" id="navPanel">
      <h1>MedHealth</h1>
      <ul data-role="listview">
        <li><%= link_to 'Visits', visits_path %></li>
        <li><%= link_to 'Patients', patients_path %></li>
        <li><%= link_to 'Physicians', physicians_path %></li>
        <li><%= link_to 'Tokens', tokens_path %></li>
      </ul>
    </div><!-- /panel -->
    <div data-role="header">
      <a href="#navPanel" class="ui-btn-left ui-btn ui-btn-inline ui-mini ui-btn ui-icon-bars ui-btn-icon-left ui-shadow ui-corner-all">Menu</a>
      <h1><%= yield :title %></h1>
      <%= yield :header %>
    </div><!-- /header -->
    <%= yield %>
    <div data-role="footer" data-position="fixed">
      <%= link_to 'Visits', visits_path %> | <%= link_to 'Patients', patients_path %> | <%= link_to 'Physicians', physicians_path %> | MedHealth App
    </div><!-- /footer -->
  </div><!-- /page -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedHealth</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="hd">
    <div style="text-align: right; padding: 10px 50px 0px 40px;;">
      <% if @current_location  %>
        <strong style="float: left; font-weight: bold; background-color: yellow; display: inline-block; padding: 2px 5px; border: solid 1px #000;"><%= @current_location.name %></strong>
      <% end %>
      <small>
        <% if user_signed_in? %>
          Welcome <%= current_user.firstname %> <%= current_user.lastname %><%= " | " if current_user.admin? %><%= link_to "Manage locations", locations_path if current_user.admin? %> | <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
          Welcome Guest, <%= link_to('Login', new_user_session_path) %>
        <% end %>
      </small>
    </div>
    <h1 id="logo">
    101 - Specimen Collection Center (Med-Health Laboratories Ltd.)
      <% if user_signed_in? %>
      <ul id="top-nav" class="top-nav">
      <li><%= link_to 'Tokens', location_tokens_path(current_location) if @current_location %></li>
      <li class="divider">|</li>
        <li><%= link_to 'Patients', root_path %></li>
        <li class="divider">|</li>
        <li><%= link_to 'Physicians', physicians_path %></li>
        <li class="divider">|</li>
        <li class="dropdown">
          <%= link_to 'Tests', tests_path %>
          <ul class="sub-menu">
            <li><%= link_to 'Manage Test Groups', test_groups_path %></li>
            <li><%= link_to 'Manage Tests', tests_path %></li>
          </ul>
        </li>
        <li class="divider">|</li>
        <li class="dropdown">
          <%= link_to 'Reports', reports_index_path %>
          <ul class="sub-menu">
            <li><%= link_to 'Patient Waiting Reports', reports_index_path %></li>
            <li><%= link_to 'Test Statistics', reports_test_statistic_path %></li>
            <li><%= link_to 'Summary', reports_summary_path %></li>
            <li><%= link_to 'Patients by physician', reports_physician_patients_path %></li>
            <li><%= link_to 'Peak Time', reports_peak_time_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </h1>
  </div>

  <div id="pg">
   <div id="bd">
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>

  <div id="ft">
    <% if user_signed_in? %>
    <p>
    <%= link_to 'Patients', root_path %> | <%= link_to 'Physicians', physicians_path %> | <%= link_to 'Tokens', location_tokens_path(current_location) if @current_location %> | <%= link_to 'Reports', reports_index_path %>  | <%= link_to 'Tests', tests_path %> | MedHealth App
    </p>
    <% end %>
    <div id="dialog-confirm" style="display: none;" title="VERIFY PI INFORMATION ENTERED">
    <div id="patient-details">
      <h1 id="name">
        <span id="p_name"></span>
        <ul>
          <li>OHIP: <span id="p_ohip"></span>&nbsp;<span id="p_vc"></span></li>
          <li class="expire">Expires on: <span id="p_hed"></span></li>
        </ul>
      </h1>
      <h2 id="heading">
        <span id="p_gender"></span><br />
        Birthdate: <span id="p_bdate"></span>
      </h2>
      <div class="address-details">
        <div id="p_address" class="address">
        </div>
        <div id="p_contact" class="contact">
        </div>
        <div class="clear">
        </div>
      </div>
      <h3>Physician: <span id="p_physician"></span></h3>
      <h4>Visit date: <span id="p_visitdate"></span></h4>
      <h4>Payment program: <span id="p_payment_program"></span></h4>
      <hr />
      <h4>Tests:</h4>
      <table id="selected_tests"></table>
    </div>
    </div>
  </div>

</body>
</html>